spring.application.name=ems-backend
# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/ems
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
# Prometheus
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true
